/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ui.panels;

/**
 *
 * @author EREN
 */
import com.mycompany.CalcBackend.RandomNumber;
import com.mycompany.auxilaryforms.NumberAnalyse;
import com.mycompany.auxilaryforms.UnitConverter;

public class CalcMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form CalcMenuPanel
     */
    public CalcMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customButtonMain3 = new com.mycompany.buttons.CustomButtonMain();
        customButtonMain5 = new com.mycompany.buttons.CustomButtonMain();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        numAnalyseToolBtn = new com.mycompany.buttons.CustomButtonMain();
        unitConverterBtn = new com.mycompany.buttons.CustomButtonMain();
        randomNumGeneratorBtn = new com.mycompany.buttons.CustomButtonMain();

        customButtonMain3.setForeground(new java.awt.Color(255, 255, 255));
        customButtonMain3.setText("Grafik Çizici");
        customButtonMain3.setColor(new java.awt.Color(70, 129, 244));
        customButtonMain3.setColorClick(new java.awt.Color(87, 131, 219));
        customButtonMain3.setColorOver(new java.awt.Color(85, 194, 218));
        customButtonMain3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        customButtonMain3.setRadius(10);
        customButtonMain3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButtonMain3ActionPerformed(evt);
            }
        });

        customButtonMain5.setForeground(new java.awt.Color(255, 255, 255));
        customButtonMain5.setText("Birim Dönüştürücü");
        customButtonMain5.setToolTipText("");
        customButtonMain5.setColor(new java.awt.Color(70, 129, 244));
        customButtonMain5.setColorClick(new java.awt.Color(87, 131, 219));
        customButtonMain5.setColorOver(new java.awt.Color(85, 194, 218));
        customButtonMain5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        customButtonMain5.setRadius(10);
        customButtonMain5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButtonMain5ActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(45, 45, 45));
        setPreferredSize(new java.awt.Dimension(655, 57));

        numAnalyseToolBtn.setBackground(new java.awt.Color(63, 182, 242));
        numAnalyseToolBtn.setForeground(new java.awt.Color(30, 30, 30));
        numAnalyseToolBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\analysing30x30.png")); // NOI18N
        numAnalyseToolBtn.setText("Sayı Analiz Aracı");
        numAnalyseToolBtn.setToolTipText("");
        numAnalyseToolBtn.setBorderPainted(false);
        numAnalyseToolBtn.setColor(new java.awt.Color(63, 182, 242));
        numAnalyseToolBtn.setColorClick(new java.awt.Color(45, 160, 230));
        numAnalyseToolBtn.setColorOver(new java.awt.Color(70, 160, 225));
        numAnalyseToolBtn.setFocusPainted(false);
        numAnalyseToolBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        numAnalyseToolBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numAnalyseToolBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        numAnalyseToolBtn.setIconTextGap(50);
        numAnalyseToolBtn.setRadius(10);
        numAnalyseToolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAnalyseToolBtnActionPerformed(evt);
            }
        });

        unitConverterBtn.setBackground(new java.awt.Color(63, 182, 242));
        unitConverterBtn.setForeground(new java.awt.Color(30, 30, 30));
        unitConverterBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\convert30x30.png")); // NOI18N
        unitConverterBtn.setText("Birim Dönüştürücü");
        unitConverterBtn.setToolTipText("");
        unitConverterBtn.setBorderPainted(false);
        unitConverterBtn.setColor(new java.awt.Color(63, 182, 242));
        unitConverterBtn.setColorClick(new java.awt.Color(45, 160, 230));
        unitConverterBtn.setColorOver(new java.awt.Color(70, 160, 225));
        unitConverterBtn.setFocusPainted(false);
        unitConverterBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        unitConverterBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unitConverterBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        unitConverterBtn.setIconTextGap(32);
        unitConverterBtn.setRadius(10);
        unitConverterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitConverterBtnActionPerformed(evt);
            }
        });

        randomNumGeneratorBtn.setBackground(new java.awt.Color(63, 182, 242));
        randomNumGeneratorBtn.setForeground(new java.awt.Color(30, 30, 30));
        randomNumGeneratorBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\surprise-box30x30.png")); // NOI18N
        randomNumGeneratorBtn.setText("Rastgele Sayı Üretici");
        randomNumGeneratorBtn.setToolTipText("");
        randomNumGeneratorBtn.setBorderPainted(false);
        randomNumGeneratorBtn.setColor(new java.awt.Color(63, 182, 242));
        randomNumGeneratorBtn.setColorClick(new java.awt.Color(45, 160, 230));
        randomNumGeneratorBtn.setColorOver(new java.awt.Color(70, 160, 225));
        randomNumGeneratorBtn.setFocusPainted(false);
        randomNumGeneratorBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        randomNumGeneratorBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        randomNumGeneratorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        randomNumGeneratorBtn.setIconTextGap(23);
        randomNumGeneratorBtn.setRadius(10);
        randomNumGeneratorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomNumGeneratorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(randomNumGeneratorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitConverterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numAnalyseToolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomNumGeneratorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitConverterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numAnalyseToolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numAnalyseToolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAnalyseToolBtnActionPerformed
        NumberAnalyse na = new NumberAnalyse();
        na.setVisible(true);
    }//GEN-LAST:event_numAnalyseToolBtnActionPerformed

    private void customButtonMain3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButtonMain3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customButtonMain3ActionPerformed

    private void customButtonMain5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButtonMain5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customButtonMain5ActionPerformed

    private void unitConverterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitConverterBtnActionPerformed
       UnitConverter uc = new UnitConverter();
       uc.setVisible(true);
    }//GEN-LAST:event_unitConverterBtnActionPerformed

    private void randomNumGeneratorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomNumGeneratorBtnActionPerformed
       RandomNumber rm = new RandomNumber();
    }//GEN-LAST:event_randomNumGeneratorBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.buttons.CustomButtonMain customButtonMain3;
    private com.mycompany.buttons.CustomButtonMain customButtonMain5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private com.mycompany.buttons.CustomButtonMain numAnalyseToolBtn;
    private com.mycompany.buttons.CustomButtonMain randomNumGeneratorBtn;
    private com.mycompany.buttons.CustomButtonMain unitConverterBtn;
    // End of variables declaration//GEN-END:variables
}
