/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.auxilaryforms;

import com.mycompany.CalcBackend.CalcButtonListener;
import com.mycompany.CalcBackend.FormulaButtonListener;
import com.mycompany.buttons.CustomButtonForFormulaForm;
import com.mycompany.buttons.CustomButtonMain;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author EREN
 */
public class FormulaForm extends javax.swing.JFrame {
    private int xOffset = 0;
    private int yOffset = 0;
    
     private FormulaButtonListener buttonListener = new FormulaButtonListener(null);
    
    /**
     * Creates new form FormulaForm
     */
    public FormulaForm() {
    this(null); 
    }

    public FormulaForm(CalcButtonListener clcbl) {
        setUndecorated(true);
        
        initComponents();
        
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        
         addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                xOffset = e.getX();
                yOffset = e.getY();
            }
        });

        
        
        addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                int x = e.getXOnScreen() - xOffset;
                int y = e.getYOnScreen() - yOffset;
                setLocation(x, y);
            }
        });
        
        
        buttonListener = new FormulaButtonListener(clcbl);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.setBorder(new EmptyBorder(50, 0, 0, 0));
        buttonPanel.setBackground(new Color(45,45,45));
        buttonPanel.setLayout(new FlowLayout());


        
        
        String[] buttonTexts = {
                    "Faktöriyel Hesaplama", "Binom Hesaplama", "Üslü Sayı Hesaplama",
                    "İki Nokta Arasındaki Mesafeyi Hesaplama", "İki Noktanın Orta Noktasını Hesaplama",
                    "Kosinüs Teoremi", "Permütasyon Hesaplama", "Kombinasyon Hesaplama",
                    "Öklid Teoremi", "Üçgen G noktası bulma(kordinatlarla)", "Pisagor Teoremi",
                    "Sinüs Hesaplama", "Kosinüs Hesaplama", "Tanjant Hesaplama", "Kotanjant Hesaplama",
                    "Sekant Hesaplama", "Kosekant Hesaplama", "Hiperbolik Sinüs Hesaplama",
                    "Hiperbolik Kosinüs Hesaplama", "Hiperbolik Tanjant Hesaplama",
                    "Hiperbolik Kotanjant Hesaplama", "Hiperbolik Sekant Hesaplama",
                    "Hiperbolik Kosekant Hesaplama", "Çokgen İç Açı Hesabı","Rasyonel-Ondalık Çevirici"
                };        
         for (String text : buttonTexts) {
            CustomButtonForFormulaForm button = new CustomButtonForFormulaForm(text);
            button.addActionListener((ActionEvent e) -> {
                buttonListener.handleButtonClick(text);
            });
            buttonPanel.add(button);
         }
         
        add(buttonPanel, BorderLayout.CENTER);
        setLocationRelativeTo(null);
     
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        closeBtn = new com.mycompany.buttons.CustomButtonMain();
        minimizeBtn = new com.mycompany.buttons.CustomButtonMain();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(24, 24, 32));

        closeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\close.png")); // NOI18N
        closeBtn.setBorderColor(new java.awt.Color(24, 24, 32));
        closeBtn.setColor(new java.awt.Color(231, 76, 60));
        closeBtn.setColorClick(new java.awt.Color(153, 39, 27));
        closeBtn.setColorOver(new java.awt.Color(192, 57, 43));
        closeBtn.setMargin(new java.awt.Insets(6, 6, 6, 6));
        closeBtn.setRadius(50);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        minimizeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\minus.png")); // NOI18N
        minimizeBtn.setBorderColor(new java.awt.Color(24, 24, 32));
        minimizeBtn.setColor(new java.awt.Color(63, 182, 242));
        minimizeBtn.setColorClick(new java.awt.Color(30, 120, 180));
        minimizeBtn.setColorOver(new java.awt.Color(45, 145, 200));
        minimizeBtn.setMargin(new java.awt.Insets(6, 6, 6, 6));
        minimizeBtn.setRadius(50);
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(600, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 386, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormulaForm().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.buttons.CustomButtonMain closeBtn;
    private javax.swing.JPanel jPanel3;
    private com.mycompany.buttons.CustomButtonMain minimizeBtn;
    // End of variables declaration//GEN-END:variables
}
