/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.auxilaryforms;

import com.mycompany.CalcBackend.primeFactor;
import com.mycompany.CalcBackend.primeNumber;
import com.mycompany.CalcBackend.findMultipliers;
import com.mycompany.CalcBackend.arithmeticMean;
import com.mycompany.CalcBackend.geometricMean;
import com.mycompany.CalcBackend.harmonicMean;
import com.mycompany.CalcBackend.medianBtnBackend;
import com.mycompany.CalcBackend.modeBtnBackend;
import com.mycompany.CalcBackend.Variance;
import com.mycompany.CalcBackend.StandardDeviation;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
/**
 *
 * @author EREN
 */
public class NumberAnalyse extends javax.swing.JFrame {
     private int xOffset = 0;
     private int yOffset = 0;
    
    /**
     * Creates new form NumberAnalyse
     */
    public NumberAnalyse() {
        setUndecorated(true);
        
        initComponents();
        
        titleLabel.setText("<html><font color='white'>Sayı Analiz Aracı</font></html>");
        
        setLocationRelativeTo(null);
        
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
         
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                xOffset = e.getX();
                yOffset = e.getY();
            }
        });

        
        
        addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                int x = e.getXOnScreen() - xOffset;
                int y = e.getYOnScreen() - yOffset;
                setLocation(x, y);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        primeFactorButton = new com.mycompany.buttons.CustomButtonMain();
        foundMultipliersBtn = new com.mycompany.buttons.CustomButtonMain();
        primeNumberControlBtn = new com.mycompany.buttons.CustomButtonMain();
        arithmeticMeanBtn = new com.mycompany.buttons.CustomButtonMain();
        geometricMeanBtn = new com.mycompany.buttons.CustomButtonMain();
        harmonicMeanBtn = new com.mycompany.buttons.CustomButtonMain();
        medianBtn = new com.mycompany.buttons.CustomButtonMain();
        modeBtn = new com.mycompany.buttons.CustomButtonMain();
        varianceBtn = new com.mycompany.buttons.CustomButtonMain();
        standardDeviationBtn = new com.mycompany.buttons.CustomButtonMain();
        jPanel3 = new javax.swing.JPanel();
        closeBtn = new com.mycompany.buttons.CustomButtonMain();
        minimizeBtn = new com.mycompany.buttons.CustomButtonMain();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));

        primeFactorButton.setForeground(new java.awt.Color(255, 255, 255));
        primeFactorButton.setText("Asal Çarpanları");
        primeFactorButton.setBorderPainted(false);
        primeFactorButton.setColorOver(new java.awt.Color(102, 153, 255));
        primeFactorButton.setFocusPainted(false);
        primeFactorButton.setRadius(10);
        primeFactorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeFactorButtonActionPerformed(evt);
            }
        });

        foundMultipliersBtn.setForeground(new java.awt.Color(255, 255, 255));
        foundMultipliersBtn.setText("Bölenlerini Bulma");
        foundMultipliersBtn.setBorderPainted(false);
        foundMultipliersBtn.setColorOver(new java.awt.Color(102, 153, 255));
        foundMultipliersBtn.setFocusPainted(false);
        foundMultipliersBtn.setRadius(10);
        foundMultipliersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foundMultipliersBtnActionPerformed(evt);
            }
        });

        primeNumberControlBtn.setForeground(new java.awt.Color(255, 255, 255));
        primeNumberControlBtn.setText("Asal Sayı Kontorlü");
        primeNumberControlBtn.setBorderPainted(false);
        primeNumberControlBtn.setColorOver(new java.awt.Color(102, 153, 255));
        primeNumberControlBtn.setFocusPainted(false);
        primeNumberControlBtn.setRadius(10);
        primeNumberControlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeNumberControlBtnActionPerformed(evt);
            }
        });

        arithmeticMeanBtn.setForeground(new java.awt.Color(255, 255, 255));
        arithmeticMeanBtn.setText("Aritmetik Ortalama");
        arithmeticMeanBtn.setBorderPainted(false);
        arithmeticMeanBtn.setColorOver(new java.awt.Color(102, 153, 255));
        arithmeticMeanBtn.setFocusPainted(false);
        arithmeticMeanBtn.setRadius(10);
        arithmeticMeanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arithmeticMeanBtnActionPerformed(evt);
            }
        });

        geometricMeanBtn.setForeground(new java.awt.Color(255, 255, 255));
        geometricMeanBtn.setText("Geometrik Ortalama");
        geometricMeanBtn.setBorderPainted(false);
        geometricMeanBtn.setColorOver(new java.awt.Color(102, 153, 255));
        geometricMeanBtn.setFocusPainted(false);
        geometricMeanBtn.setRadius(10);
        geometricMeanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geometricMeanBtnActionPerformed(evt);
            }
        });

        harmonicMeanBtn.setForeground(new java.awt.Color(255, 255, 255));
        harmonicMeanBtn.setText("Harmonik Ortalama");
        harmonicMeanBtn.setBorderPainted(false);
        harmonicMeanBtn.setColorOver(new java.awt.Color(102, 153, 255));
        harmonicMeanBtn.setFocusPainted(false);
        harmonicMeanBtn.setRadius(10);
        harmonicMeanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harmonicMeanBtnActionPerformed(evt);
            }
        });

        medianBtn.setForeground(new java.awt.Color(255, 255, 255));
        medianBtn.setText("Medyan");
        medianBtn.setBorderPainted(false);
        medianBtn.setColorOver(new java.awt.Color(102, 153, 255));
        medianBtn.setFocusPainted(false);
        medianBtn.setRadius(10);
        medianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianBtnActionPerformed(evt);
            }
        });

        modeBtn.setForeground(new java.awt.Color(255, 255, 255));
        modeBtn.setText("Mod");
        modeBtn.setBorderPainted(false);
        modeBtn.setColorOver(new java.awt.Color(102, 153, 255));
        modeBtn.setFocusPainted(false);
        modeBtn.setRadius(10);
        modeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeBtnActionPerformed(evt);
            }
        });

        varianceBtn.setForeground(new java.awt.Color(255, 255, 255));
        varianceBtn.setText("Varyans");
        varianceBtn.setBorderPainted(false);
        varianceBtn.setColorOver(new java.awt.Color(102, 153, 255));
        varianceBtn.setFocusPainted(false);
        varianceBtn.setRadius(10);
        varianceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varianceBtnActionPerformed(evt);
            }
        });

        standardDeviationBtn.setForeground(new java.awt.Color(255, 255, 255));
        standardDeviationBtn.setText("Standart Sapma");
        standardDeviationBtn.setToolTipText("");
        standardDeviationBtn.setBorderPainted(false);
        standardDeviationBtn.setColorOver(new java.awt.Color(102, 153, 255));
        standardDeviationBtn.setFocusPainted(false);
        standardDeviationBtn.setRadius(10);
        standardDeviationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardDeviationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(arithmeticMeanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(geometricMeanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(harmonicMeanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(primeFactorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(primeNumberControlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(foundMultipliersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(medianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(varianceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(standardDeviationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primeFactorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primeNumberControlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foundMultipliersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arithmeticMeanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geometricMeanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harmonicMeanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varianceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standardDeviationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(24, 24, 32));

        closeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\close.png")); // NOI18N
        closeBtn.setBorderColor(new java.awt.Color(24, 24, 32));
        closeBtn.setBorderPainted(false);
        closeBtn.setColor(new java.awt.Color(231, 76, 60));
        closeBtn.setColorClick(new java.awt.Color(153, 39, 27));
        closeBtn.setColorOver(new java.awt.Color(192, 57, 43));
        closeBtn.setFocusPainted(false);
        closeBtn.setMargin(new java.awt.Insets(6, 6, 6, 6));
        closeBtn.setRadius(50);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        minimizeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\minus.png")); // NOI18N
        minimizeBtn.setBorderColor(new java.awt.Color(24, 24, 32));
        minimizeBtn.setBorderPainted(false);
        minimizeBtn.setColorClick(new java.awt.Color(30, 120, 180));
        minimizeBtn.setColorOver(new java.awt.Color(45, 145, 200));
        minimizeBtn.setFocusPainted(false);
        minimizeBtn.setMargin(new java.awt.Insets(6, 6, 6, 6));
        minimizeBtn.setRadius(50);
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\analysing30x30.png")); // NOI18N
        titleLabel.setText("  Sayı Analiz Aracı");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primeFactorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeFactorButtonActionPerformed
        primeFactor pf = new primeFactor();
        pf.setVisible(true);
    }//GEN-LAST:event_primeFactorButtonActionPerformed

    private void foundMultipliersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foundMultipliersBtnActionPerformed
       findMultipliers fm = new findMultipliers();
       fm.setVisible(true);
    }//GEN-LAST:event_foundMultipliersBtnActionPerformed

    private void primeNumberControlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeNumberControlBtnActionPerformed
         primeNumber pn = new primeNumber();
         pn.setVisible(true);
    }//GEN-LAST:event_primeNumberControlBtnActionPerformed

    private void arithmeticMeanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arithmeticMeanBtnActionPerformed
       arithmeticMean am = new arithmeticMean();
       am.setVisible(true);
    }//GEN-LAST:event_arithmeticMeanBtnActionPerformed

    private void geometricMeanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geometricMeanBtnActionPerformed
        geometricMean gm = new geometricMean();
        gm.setVisible(true);
    }//GEN-LAST:event_geometricMeanBtnActionPerformed

    private void harmonicMeanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harmonicMeanBtnActionPerformed
        harmonicMean hm = new harmonicMean();
        hm.setVisible(true);
    }//GEN-LAST:event_harmonicMeanBtnActionPerformed

    private void medianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianBtnActionPerformed
        medianBtnBackend mbb = new medianBtnBackend();
        mbb.setVisible(true);
    }//GEN-LAST:event_medianBtnActionPerformed

    private void modeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeBtnActionPerformed
        modeBtnBackend mobb = new modeBtnBackend();
        mobb.setVisible(true);
    }//GEN-LAST:event_modeBtnActionPerformed

    private void varianceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varianceBtnActionPerformed
       Variance v = new Variance();
       v.setVisible(true);
    }//GEN-LAST:event_varianceBtnActionPerformed

    private void standardDeviationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardDeviationBtnActionPerformed
        StandardDeviation sd = new StandardDeviation();
        sd.setVisible(true);
    }//GEN-LAST:event_standardDeviationBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberAnalyse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.buttons.CustomButtonMain arithmeticMeanBtn;
    private com.mycompany.buttons.CustomButtonMain closeBtn;
    private com.mycompany.buttons.CustomButtonMain foundMultipliersBtn;
    private com.mycompany.buttons.CustomButtonMain geometricMeanBtn;
    private com.mycompany.buttons.CustomButtonMain harmonicMeanBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private com.mycompany.buttons.CustomButtonMain medianBtn;
    private com.mycompany.buttons.CustomButtonMain minimizeBtn;
    private com.mycompany.buttons.CustomButtonMain modeBtn;
    private com.mycompany.buttons.CustomButtonMain primeFactorButton;
    private com.mycompany.buttons.CustomButtonMain primeNumberControlBtn;
    private com.mycompany.buttons.CustomButtonMain standardDeviationBtn;
    private javax.swing.JLabel titleLabel;
    private com.mycompany.buttons.CustomButtonMain varianceBtn;
    // End of variables declaration//GEN-END:variables
}
