/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.core;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author EREN
 */
public class CalcUi extends javax.swing.JFrame {
     private int xOffset = 0;
     private int yOffset = 0;
    public CalcUi() {
        try {
            // Stil ayarları
            UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 16));
            UIManager.put("OptionPane.buttonFont", new Font("Segoe UI", Font.PLAIN, 14));
            UIManager.put("Button.background", new Color(63,182,242));
            UIManager.put("Button.foreground", Color.WHITE);
            UIManager.put("OptionPane.okButtonText", "Tamam");
            UIManager.put("OptionPane.cancelButtonText", "İptal");
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        
        setUndecorated(true);
        
        initComponents();
        
        createrLabel.setText("<html><font color='white'>By. Eren</font></html>");
        
        setLocationRelativeTo(null);
        
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                xOffset = e.getX();
                yOffset = e.getY();
            }
        });

        
        
        addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                int x = e.getXOnScreen() - xOffset;
                int y = e.getYOnScreen() - yOffset;
                setLocation(x, y);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcNumbersPanel1 = new com.mycompany.ui.panels.CalcNumbersPanel();
        jPanel1 = new javax.swing.JPanel();
        customButtonMain2 = new com.mycompany.buttons.CustomButtonMain();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        calcNumbersPanel2 = new com.mycompany.ui.panels.CalcNumbersPanel();
        jPanel3 = new javax.swing.JPanel();
        closeBtn = new com.mycompany.buttons.CustomButtonMain();
        minimizeBtn = new com.mycompany.buttons.CustomButtonMain();
        createrLabel = new javax.swing.JLabel();
        calcMenuPanel2 = new com.mycompany.ui.panels.CalcMenuPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        customButtonMain2.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\close.png")); // NOI18N
        customButtonMain2.setBorderColor(new java.awt.Color(24, 24, 32));
        customButtonMain2.setColor(new java.awt.Color(231, 76, 60));
        customButtonMain2.setMargin(new java.awt.Insets(6, 6, 6, 6));
        customButtonMain2.setRadius(50);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(24, 24, 32));

        closeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\close.png")); // NOI18N
        closeBtn.setBorderColor(new java.awt.Color(24, 24, 32));
        closeBtn.setBorderPainted(false);
        closeBtn.setColor(new java.awt.Color(231, 76, 60));
        closeBtn.setColorClick(new java.awt.Color(153, 39, 27));
        closeBtn.setColorOver(new java.awt.Color(192, 57, 43));
        closeBtn.setFocusPainted(false);
        closeBtn.setMargin(new java.awt.Insets(6, 6, 6, 6));
        closeBtn.setRadius(50);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        minimizeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\EREN\\Documents\\NetBeansProjects\\MathProjectTheCalc\\image\\minus.png")); // NOI18N
        minimizeBtn.setBorderColor(new java.awt.Color(24, 24, 32));
        minimizeBtn.setBorderPainted(false);
        minimizeBtn.setColorClick(new java.awt.Color(30, 120, 180));
        minimizeBtn.setColorOver(new java.awt.Color(45, 145, 200));
        minimizeBtn.setFocusPainted(false);
        minimizeBtn.setMargin(new java.awt.Insets(6, 6, 6, 6));
        minimizeBtn.setRadius(50);
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });

        createrLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createrLabel.setText("By. Eren");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calcNumbersPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calcMenuPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(calcNumbersPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(calcMenuPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcUi().setVisible(true);
            }
        });  
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.ui.panels.CalcMenuPanel calcMenuPanel2;
    private com.mycompany.ui.panels.CalcNumbersPanel calcNumbersPanel1;
    private com.mycompany.ui.panels.CalcNumbersPanel calcNumbersPanel2;
    private com.mycompany.buttons.CustomButtonMain closeBtn;
    private javax.swing.JLabel createrLabel;
    private com.mycompany.buttons.CustomButtonMain customButtonMain2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private com.mycompany.buttons.CustomButtonMain minimizeBtn;
    // End of variables declaration//GEN-END:variables
}
